# Site settings
title: Unfathomable Unified Rulebook
email: ursreupke@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  A unified rulebook for Unfathomable and its expansions. 
baseurl: "/UnfathomableRulebook/" # the subpath of your site, e.g. /blog/
url: "http://urskr.github.io" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
